- name: Stackify
  hosts: localhost
  vars:
    os_tasks:
      debian: tasks/debian.yml
      darwin: tasks/darwin.yml
  environment:
    ANSIBLE_STDOUT_CALLBACK: profile_tasks
  tasks:

    - name: Ensure user ansible collections directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.ansible/collections"
        state: directory
        mode: '0700'

    - name: Check if community.general collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection list
      register: installed_collections
      changed_when: false

    - name: Install community.general collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general
      when: "'community.general' not in installed_collections.stdout"
      changed_when: "'community.general' in installed_collections.stdout"

    - name: Include OS specific tasks
      ansible.builtin.include_tasks: "{{ os_tasks[stackify_os_family] }}"
