- name: Install Docker MacOS
  ansible.builtin.include_tasks: modules/docker/docker.yml

- name: Install OrbStack MacOS
  ansible.builtin.include_tasks: modules/orbstack/orbstack.yml

- name: Install git MacOS
  ansible.builtin.include_tasks: modules/git/git.yml

- name: Install PostgreSQL MacOS
  ansible.builtin.include_tasks: modules/postgresql/postgresql.yml

- name: Install MySQL MacOS
  ansible.builtin.include_tasks: modules/mysql/mysql.yml

- name: Install Redis MacOS
  ansible.builtin.include_tasks: modules/redis/redis.yml
